### ISSUE TITLE
Automatic campaigns are no longer executed

### ISSUE THREAD

**Issue by idigIT-onl** [hizzle-co/noptin#787]
### Description

If you define an automatic campaign or email that is based on a tag and/or a list, it is no longer sent. the email has a title and content and the log only shows the entry "Sending the campaign: """ - without a title or any other error.

Also the new creation of automatic campaigns with a conditional logic no longer works. no e-mail is sent.

This is the 2nd serious bug that i have reported within 48 hours. why are the updates not tested properly before they are rolled out?
At the moment I am not comfortable to implement any other Noptin installations on my customer sites.
Best regards

**Comment by picocodes** [comment]
Sorry about that. Can you please send a screenshot of the campaign in the email editor so that we take a look?

It seems like you've not set up your campaign correctly. If you're sending the campaign to a single subscriber then ensure the "Send To" panel looks like in the screenshot below:-

![scrnli_3_2_2024_6-10-04 AM](https://github.com/hizzle-co/noptin/assets/19934448/540c8c98-7a78-46fb-bbd2-81175c7056ae)

If not then provide more on what you're trying to do so that we can help further.

We sent out an email to customers explaining that version 3 is a big update and there might be bugs that we've missed. Hence why you see bugs and also why we've released 3 fixes in the past 2 weeks.

**Comment by KGIII** [comment]
I was able to 'fix' this by recreating the automated letter. Of course, it sometimes still doesn't send and I need to process the queue manually. Ah well...

**Comment by picocodes** [comment]
This may have been caused by incorrect trigger IDs during the automated-email migration introduced around Noptin 3.

We have since corrected the trigger migration and added better email error logging, queue health checks, and safeguards that recreate missing sending tasks.

If something similar happens again with the latest version, please open a new issue with the relevant logs and automated email configuration.
